/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:61df7fed-5114-429a-88cf-6d1f61d147bd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CMgW4FQgK",
    "aws_user_pools_web_client_id": "4q5t28qe7cis9d474doset10ed",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qhbjd3foavbrxk2p22di2clsge.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
