/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:61df7fed-5114-429a-88cf-6d1f61d147bd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CMgW4FQgK",
    "aws_user_pools_web_client_id": "4q5t28qe7cis9d474doset10ed",
    "oauth": {}
};


export default awsmobile;
