name: On Merge to Master
on:
  push:
    branches:
      - master
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm test
